In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("ride_sharing_raw_dataset.csv")

In [3]:
df.head()

,trip_id,pickup_datetime,dropoff_datetime,pickup_location,dropoff_location,fare_amount,distance_km,driver_id,customer_id,ride_status,payment_type,vehicle_type,surge_multiplier,rating,weather_condition
0,1,2023-03-26 16:38:00,2023-03-26 18:01:00,Pune,Chennai,225.94,4.88,1036,6867,completed,cash,sedan,2.0,3.5,Clear
1,2,2023-04-12 23:47:00,2023-04-12 23:52:00,Pune,Mumbai,486.80,19.11,1806,7476,completed,upi,mini,1.2,5.0,Storm
2,3,2023-04-02 14:52:00,2023-04-02 15:37:00,Pune,Pune,68.11,6.50,1150,6061,completed,cash,sedan,1.0,3.3,Storm
3,4,2023-09-12 01:18:00,2023-09-12 01:40:00,Chennai,Pune,209.28,14.03,1944,7854,completed,upi,sedan,1.0,3.8,Clear
4,5,2023-06-29 23:38:00,2023-06-29 23:43:00,Pune,Hyderabad,232.56,4.59,1132,7776,completed,upi,suv,1.2,3.4,Rain

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60500 entries, 0 to 60499
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   trip_id            60500 non-null  int64
 1   pickup_datetime    60500 non-null  object
 2   dropoff_datetime   60500 non-null  object
 3   pickup_location    60500 non-null  object
 4   dropoff_location   60500 non-null  object
 5   fare_amount        60500 non-null  float64
 6   distance_km        60500 non-null  float64
 7   driver_id          60500 non-null  int64
 8   customer_id        60500 non-null  int64
 9   ride_status        60500 non-null  object
 10  payment_type       60500 non-null  object
 11  vehicle_type       60500 non-null  object
 12  surge_multiplier   60500 non-null  float64
 13  rating             54451 non-null  float64
 14  weather_condition  60500 non-null  object
dtypes: float64(4), int64(3), object(8)
memory usage: 6.9+ MB

In [5]:
df.isnull().sum()

trip_id                 0
pickup_datetime         0
dropoff_datetime        0
pickup_location         0
dropoff_location        0
fare_amount             0
distance_km             0
driver_id               0
customer_id             0
ride_status             0
payment_type            0
vehicle_type            0
surge_multiplier        0
rating               6049
weather_condition       0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(500)

In [7]:
df.describe()

,trip_id,fare_amount,distance_km,driver_id,customer_id,surge_multiplier,rating
count,60500.000000,60500.000000,60500.00000,60500.000000,60500.000000,60500.000000,54451.000000
mean,29987.903851,273.504083,12.99097,1499.482512,7496.808050,1.165241,3.995835
std,17318.455546,131.164787,6.97315,288.838408,1446.516326,0.261976,0.579410
min,1.000000,-10.000000,0.00000,1000.000000,5000.000000,1.000000,3.000000
25%,14988.750000,160.525000,6.99000,1250.000000,6251.000000,1.000000,3.500000
50%,29972.500000,273.730000,12.99000,1499.000000,7487.000000,1.000000,4.000000
75%,44982.250000,386.640000,19.01250,1749.000000,8757.000000,1.200000,4.500000
max,60000.000000,499.990000,25.00000,1999.000000,9999.000000,2.000000,5.000000

In [8]:
df=df.drop_duplicates()

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df['rating']=df['rating'].fillna(df['rating'].median())

In [11]:
df.isnull().sum()

trip_id              0
pickup_datetime      0
dropoff_datetime     0
pickup_location      0
dropoff_location     0
fare_amount          0
distance_km          0
driver_id            0
customer_id          0
ride_status          0
payment_type         0
vehicle_type         0
surge_multiplier     0
rating               0
weather_condition    0
dtype: int64

In [12]:
df=df[df['fare_amount']>0]

In [14]:
df=df[df['distance_km']>0]

In [16]:
df['pickup_datetime']=pd.to_datetime(df['pickup_datetime'])
df['dropoff_datetime']=pd.to_datetime(df['dropoff_datetime'])
df['trip_duration']=(df['dropoff_datetime'] - df['pickup_datetime']).dt.total_seconds()/60

In [17]:
df=df[df['trip_duration']<180]

In [19]:
df = df[~((df['pickup_location'] != df['dropoff_location']) & (df['distance_km'] < 50))]

In [21]:
df

,trip_id,pickup_datetime,dropoff_datetime,pickup_location,dropoff_location,fare_amount,distance_km,driver_id,customer_id,ride_status,payment_type,vehicle_type,surge_multiplier,rating,weather_condition,trip_duration
2,3,2023-04-02 14:52:00,2023-04-02 15:37:00,Pune,Pune,68.11,6.50,1150,6061,completed,cash,sedan,1.0,3.3,Storm,45.0
15,16,2023-09-27 18:28:00,2023-09-27 18:39:00,Pune,Pune,207.57,2.50,1905,8027,completed,card,mini,1.0,4.0,Clear,11.0
25,26,2023-08-16 03:09:00,2023-08-16 03:46:00,Bangalore,Bangalore,493.89,4.87,1391,9274,completed,card,sedan,1.0,4.0,Fog,37.0
27,28,2023-05-19 05:21:00,2023-05-19 05:42:00,Pune,Pune,426.42,8.48,1097,7610,completed,upi,suv,1.0,3.6,Clear,21.0
37,38,2023-12-04 15:52:00,2023-12-04 17:18:00,Mumbai,Mumbai,308.90,15.75,1687,6944,completed,upi,sedan,1.5,3.5,Fog,86.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59975,59976,2023-01-12 12:28:00,2023-01-12 12:40:00,Mumbai,Mumbai,316.64,5.33,1195,5839,completed,cash,sedan,1.0,4.6,Storm,12.0
59981,59982,2023-07-10 16:37:00,2023-07-10 17:47:00,Hyderabad,Hyderabad,177.05,11.78,1148,9359,completed,upi,suv,1.0,4.6,Clear,70.0
59984,59985,2023-09-13 17:48:00,2023-09-13 18:15:00,Delhi,Delhi,129.88,22.74,1796,9281,completed,card,sedan,1.2,4.4,Clear,27.0
59986,59987,2023-07-19 01:48:00,2023-07-19 02:47:00,Chennai,Chennai,94.93,9.11,1414,8259,completed,cash,sedan,1.0,4.0,Storm,59.0
59991,59992,2023-01-09 20:24:00,2023-01-09 20:37:00,Delhi,Delhi,248.61,23.68,1897,6268,completed,upi,sedan,1.5,4.5,Clear,13.0

In [22]:
df['pickup_location']=df['pickup_location'].str.title()
df['dropoff_location']=df['dropoff_location'].str.title()

In [24]:
df['hour']=df['pickup_datetime'].dt.hour
df['day']=df['pickup_datetime'].dt.day_name()
df['month']=df['pickup_datetime'].dt.month

df['is_weekend']=df['day'].isin(['Saturday','Sunday']).astype(int)
df['revenue']=df['fare_amount']*df['surge_multiplier']
df['revenue_per_km']=df['revenue']/df['distance_km']

In [25]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 9802 entries, 2 to 59991
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   trip_id            9802 non-null   int64
 1   pickup_datetime    9802 non-null   datetime64[ns]
 2   dropoff_datetime   9802 non-null   datetime64[ns]
 3   pickup_location    9802 non-null   object
 4   dropoff_location   9802 non-null   object
 5   fare_amount        9802 non-null   float64
 6   distance_km        9802 non-null   float64
 7   driver_id          9802 non-null   int64
 8   customer_id        9802 non-null   int64
 9   ride_status        9802 non-null   object
 10  payment_type       9802 non-null   object
 11  vehicle_type       9802 non-null   object
 12  surge_multiplier   9802 non-null   float64
 13  rating             9802 non-null   float64
 14  weather_condition  9802 non-null   object
 15  trip_duration      9802 non-null   float64
 16  hour               9802 non-null   int32
 17  day                9802 non-null   object
 18  month              9802 non-null   int32
 19  is_weekend         9802 non-null   int64
 20  revenue            9802 non-null   float64
 21  revenue_per_km     9802 non-null   float64
dtypes: datetime64[ns](2), float64(7), int32(2), int64(4), object(7)
memory usage: 1.6+ MB

,trip_id,pickup_datetime,dropoff_datetime,fare_amount,distance_km,driver_id,customer_id,surge_multiplier,rating,trip_duration,hour,month,is_weekend,revenue,revenue_per_km
count,9802.000000,9802,9802,9802.000000,9802.000000,9802.000000,9802.000000,9802.000000,9802.000000,9802.000000,9802.000000,9802.000000,9802.000000,9802.000000,9802.000000
mean,30123.728933,2023-07-01 15:24:03.005509120,2023-07-01 16:11:04.015506944,276.090568,12.925927,1504.196797,7497.770047,1.164579,3.998704,47.016833,11.417364,6.503061,0.282085,322.095880,43.246996
min,3.000000,2023-01-01 00:43:00,2023-01-01 01:48:00,50.020000,1.000000,1000.000000,5000.000000,1.000000,3.000000,5.000000,0.000000,1.000000,0.000000,50.140000,2.099875
25%,15072.500000,2023-04-01 06:32:00,2023-04-01 07:06:30,162.912500,7.000000,1253.000000,6272.250000,1.000000,3.600000,26.000000,5.000000,4.000000,0.000000,181.669500,14.028535
50%,30138.500000,2023-07-01 05:21:00,2023-07-01 05:54:00,276.835000,12.820000,1507.000000,7502.000000,1.000000,4.000000,47.000000,11.000000,7.000000,0.000000,311.070000,24.377999
75%,45136.750000,2023-10-02 08:15:00,2023-10-02 09:32:30,387.237500,18.940000,1751.000000,8742.000000,1.200000,4.400000,68.000000,17.000000,10.000000,1.000000,438.041250,46.226327
max,59992.000000,2023-12-30 21:26:00,2023-12-30 21:55:00,499.990000,25.000000,1999.000000,9999.000000,2.000000,5.000000,89.000000,23.000000,12.000000,1.000000,999.840000,881.682243
std,17398.109082,NaN,NaN,130.008924,6.917040,288.394910,1438.498503,0.263100,0.546866,24.475100,6.900310,3.444110,0.450038,172.639822,58.813192

In [26]:
df.head()

,trip_id,pickup_datetime,dropoff_datetime,pickup_location,dropoff_location,fare_amount,distance_km,driver_id,customer_id,ride_status,...,surge_multiplier,rating,weather_condition,trip_duration,hour,day,month,is_weekend,revenue,revenue_per_km
2,3,2023-04-02 14:52:00,2023-04-02 15:37:00,Pune,Pune,68.11,6.50,1150,6061,completed,...,1.0,3.3,Storm,45.0,14,Sunday,4,1,68.11,10.478462
15,16,2023-09-27 18:28:00,2023-09-27 18:39:00,Pune,Pune,207.57,2.50,1905,8027,completed,...,1.0,4.0,Clear,11.0,18,Wednesday,9,0,207.57,83.028000
25,26,2023-08-16 03:09:00,2023-08-16 03:46:00,Bangalore,Bangalore,493.89,4.87,1391,9274,completed,...,1.0,4.0,Fog,37.0,3,Wednesday,8,0,493.89,101.414784
27,28,2023-05-19 05:21:00,2023-05-19 05:42:00,Pune,Pune,426.42,8.48,1097,7610,completed,...,1.0,3.6,Clear,21.0,5,Friday,5,0,426.42,50.285377
37,38,2023-12-04 15:52:00,2023-12-04 17:18:00,Mumbai,Mumbai,308.90,15.75,1687,6944,completed,...,1.5,3.5,Fog,86.0,15,Monday,12,0,463.35,29.419048

In [27]:
df.to_csv("cleaned_rides.csv", index=False)